name: 'Echo Parameter Action'
description: 'A custom action to echo a parameter'
inputs:
  message:
    description: 'The message to echo'
    required: true
    default: 'No message provided'
runs:
  using: 'composite'
  steps:
    - name: "Parameters"
      shell: bash
      run: echo "${{ inputs.message }}"
