name: 'Custom Actions Workflow'

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-custom-actions:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Infra Congiguration'
        uses: ./.github/actions/InfraConfig

      - name: 'Build'
        run: | 
          echo "Building"

      - name: 'Deploy'
        run: | 
          echo "Deploying"

      - name: 'Tests'
        uses: ./.github/actions/Tests
        with:
          Test1: 'Sonnarqube'
          Test2: 'JUnit'
